### PR TITLE
Add CI & Update doc

### PR DESCRIPTION
**Pull request by erikmd**
This PR adds CI, doc and related files thanks to the coq-community templates and a new `meta.yml` file.

I propose to merge this in a couple of days, then make a release for Coq 8.11.

Cc @herbelin, @Zimmi48, @palmskog could some of you proof-read that PR?

### CODE REVIEW

**Comment by palmskog** [comment]
@erikmd I would switch out the `Makefile` for [this one](https://github.com/coq-community/huffman/blob/4159777f378f55587e833cfe8e479ffaac18a233/Makefile), which is more idiomatic and better supports incremental tasks in `Makefile.coq.local` if you add that in the future. (Feel free to remove the `@`s if you want to see commands though.

You also probably don't need `index.md`, which is only if you want to make a (static HTML) website, which is not something needed right away.

The author stuff in documentation should in my opinion be removed, you already get this in early in README.md and elsewhere.

**Comment by erikmd** [comment]
Thanks @palmskog for your feedback, I'll push a new version soon.

BTW regarding the CI build, do we need to perform a specific action or should be expect the CI enables automatically when the `.travis.yml` file will be part of the master branch?

**Comment by palmskog** [comment]
> BTW regarding the CI build, do we need to perform a specific action or should be expect the CI enables automatically when the `.travis.yml` file will be part of the master branch?

Yes, in all projects I know that have been moved to coq-community, it has been sufficient to add a proper `.travis.yml` on `master` to get the usual CI. I think it works on other branches as well.

**Comment by palmskog** [comment]
From a quick inspection of the source (`.v`) files, it looks like the license is `LGPL-2.1-or-later` rather than, as in the current `meta.yml`, `LGPL-2.1-only`.

**Comment by erikmd** [comment]
@palmskog 

> it looks like the license is `LGPL-2.1-or-later` rather than, as in the current meta.yml, `LGPL-2.1-only`

good catch! I just force-pushed to fix this.

**Comment by erikmd** [comment]
I've just read the README again (the latest version is available at [this URL](https://github.com/coq-community/coqoban/blob/d836c22d175b83295cce5bc1e9f80b220e81699c/README.md)), I believe the PR is ready, so if no one objects, I'll merge it on tomorrow Thursday 12 March

**Comment by erikmd** [comment]
BTW should we keep the [description](https://github.com/coq-community/coqoban/blob/master/description) file, given its contents are now subsumed by `meta.yml` and `coq-coqoban.opam` (except possibly for the "date" and "institution")?

**Comment by erikmd** [comment]
Regarding my last comment, I propose to keep the `description` file as is for now, we'll be able to move-or-remove its contents later on after the release.

**Pull request merged**
